# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-03 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
