# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-04 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20190904_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(verbose_name='网站'),
        ),
    ]
